### PR TITLE
fix: skip auth step, pass credentials to scan

### LINKED ISSUE #405: Skip `auth` step, pass auth parameters to `scan`
Running with the new v1 CLI, we see:

> Auth is done automatically when running a scan, no need to run this command.
> please add the auth parameters to the scan command

So it looks like we could skip the `auth` step and just pass the parameters to `scan` instead.

### PR DESCRIPTION
**Pull request by pbrisbin**
> [!NOTE]
> There are a few pre- and post-factor commits, so feel to review individually.

Wiz is deprecating the v0 CLI and Service Account credentials. Users are
required to migrate to Deployment credentials by June 1st.

https://docs.wiz.io/docs/set-up-wiz-cli#create-a-wiz-cli-deployment

The new, v1 CLI has some backwards-compatible support for the Service
Account credentials in the sub-commands we use here:

```sh
# What we used before this commit. Works with Service Account creds, but
# fails with Deployment creds. Shows a warning about auth not being needed.
auth <credentials>
docker scan --image <image>

# What everyone has to use after June 1st. Only works with Deployment creds,
# fails if given Service Account creds.
scan container-image <image> <credentials>

# Works with *either* Service Account or Deployment creds, shows no warnings, but
# expected to stop working after June 1st
docker scan --image <image> <credentials>
```

My plan is to leave `@v2` of this action in that state, and release
`@v3` as a breaking change that uses `scan container-image`, while also
moving to environment variables for the credentials.

Closes https://github.com/freckle/wiz-action/issues/405.

### CODE REVIEW

File: src/wiz-cli.ts [hunk 1]
```diff
@@ -12,29 +12,23 @@ class WizCLI {
   wizcli: string;
   credentials: WizCredentials;
 
-  constructor(wizcli: string, credentials: WizCredentials) {
+  constructor(
+    wizcli: string,
+    credentials: WizCredentials,
+    isServiceAccount?: boolean,
```
Comment (pbrisbin) [inline src/wiz-cli.ts]: Oops. This was from an earlier change, will remove.

**Review by danroyo — APPROVED** [review]
